"""CLA / سیلا — curated seed data: common laboratory starting materials.

Spec 01 §4 requires a rich pre-loaded set: the 12 mandated solvents, the
mandated acids & bases, plus common reagents and simple building blocks.

Data policy (spec 00: scientific honesty):
* SMILES is the single source of truth — InChI/InChIKey/formula/MW are
  computed by RDKit at seed time, never hand-typed.
* CAS numbers, GHS H-codes and physical properties are curated from common
  reference knowledge; quantities are plausible lab defaults. Users should
  verify against their supplier SDS before practical work (the UI says so).
* GHS lists are the principal hazards, not necessarily exhaustive.
* Regulatory/dual-use precursors carry an explicit note.

Field legend per entry:
  en, fa     — names;  smi — SMILES;  cas — CAS number
  syn        — synonyms (en/fa mixed);  ghs — H-codes
  qty, unit, min — default stock;  notes — safety/storage/regulatory notes
  mp, bp, d  — melting/boiling point (°C), density (g/mL) where well known
  app        — appearance
"""

from __future__ import annotations

SEED_COMPOUNDS: list[dict] = [
    # ============================= SOLVENTS ================================
    dict(en="Water (distilled)", fa="آب مقطر", smi="O", cas="7732-18-5",
         syn=["water", "aqua", "آب"], ghs=[], qty=5000, unit="mL", min=500,
         mp=0.0, bp=100.0, d=1.000, app="Colorless liquid / مایع بی‌رنگ"),
    dict(en="Ethanol", fa="اتانول", smi="CCO", cas="64-17-5",
         syn=["ethyl alcohol", "EtOH", "الکل اتیلیک"],
         ghs=["H225", "H319"], qty=2500, unit="mL", min=250,
         bp=78.4, d=0.789, app="Colorless liquid / مایع بی‌رنگ",
         notes="Highly flammable; keep away from ignition sources."),
    dict(en="Methanol", fa="متانول", smi="CO", cas="67-56-1",
         syn=["methyl alcohol", "MeOH", "الکل متیلیک"],
         ghs=["H225", "H301", "H311", "H331", "H370"], qty=2500, unit="mL", min=250,
         bp=64.7, d=0.792, app="Colorless liquid / مایع بی‌رنگ",
         notes="TOXIC — can cause blindness; handle in fume hood."),
    dict(en="Acetone", fa="استون", smi="CC(C)=O", cas="67-64-1",
         syn=["propan-2-one", "dimethyl ketone"],
         ghs=["H225", "H319", "H336"], qty=2500, unit="mL", min=250,
         bp=56.1, d=0.784, app="Colorless liquid / مایع بی‌رنگ",
         notes="Regulated solvent precursor in some jurisdictions."),
    dict(en="Dichloromethane (DCM)", fa="دی‌کلرومتان", smi="ClCCl", cas="75-09-2",
         syn=["methylene chloride", "DCM", "CH2Cl2"],
         ghs=["H315", "H319", "H336", "H351"], qty=2500, unit="mL", min=250,
         bp=39.6, d=1.327, app="Colorless liquid / مایع بی‌رنگ",
         notes="Use in fume hood; suspected carcinogen."),
    dict(en="Tetrahydrofuran (THF)", fa="تتراهیدروفوران", smi="C1CCOC1", cas="109-99-9",
         syn=["THF", "oxolane"],
         ghs=["H225", "H302", "H319", "H335"], qty=1000, unit="mL", min=100,
         bp=66.0, d=0.883, app="Colorless liquid / مایع بی‌رنگ",
         notes="Forms explosive peroxides on storage — check before distilling."),
    dict(en="Diethyl ether", fa="دی‌اتیل اتر", smi="CCOCC", cas="60-29-7",
         syn=["ether", "Et2O", "اتر"],
         ghs=["H224", "H302", "H336"], qty=1000, unit="mL", min=100,
         bp=34.6, d=0.713, app="Colorless liquid / مایع بی‌رنگ",
         notes="Extremely flammable; peroxide former; regulated precursor."),
    dict(en="n-Hexane", fa="نرمال هگزان", smi="CCCCCC", cas="110-54-3",
         syn=["hexane", "هگزان"],
         ghs=["H225", "H304", "H315", "H336", "H410"], qty=2500, unit="mL", min=250,
         bp=68.7, d=0.661, app="Colorless liquid / مایع بی‌رنگ"),
    dict(en="Ethyl acetate", fa="اتیل استات", smi="CCOC(C)=O", cas="141-78-6",
         syn=["EtOAc", "ethyl ethanoate"],
         ghs=["H225", "H319", "H336"], qty=2500, unit="mL", min=250,
         bp=77.1, d=0.902, app="Colorless liquid / مایع بی‌رنگ"),
    dict(en="Acetonitrile", fa="استونیتریل", smi="CC#N", cas="75-05-8",
         syn=["MeCN", "methyl cyanide"],
         ghs=["H225", "H302", "H312", "H319", "H332", "H412"], qty=1000, unit="mL", min=100,
         bp=81.6, d=0.786, app="Colorless liquid / مایع بی‌رنگ"),
    dict(en="Dimethyl sulfoxide (DMSO)", fa="دی‌متیل سولفوکسید", smi="CS(C)=O", cas="67-68-5",
         syn=["DMSO"], ghs=[], qty=1000, unit="mL", min=100,
         mp=18.5, bp=189.0, d=1.100, app="Colorless liquid / مایع بی‌رنگ",
         notes="Penetrates skin rapidly — carries dissolved substances with it."),
    dict(en="Dimethylformamide (DMF)", fa="دی‌متیل فرمامید", smi="CN(C)C=O", cas="68-12-2",
         syn=["DMF", "N,N-dimethylformamide"],
         ghs=["H360D"], qty=1000, unit="mL", min=100,
         bp=153.0, d=0.944, app="Colorless liquid / مایع بی‌رنگ",
         notes="Reproductive toxicant — avoid skin contact; fume hood."),
    dict(en="Toluene", fa="تولوئن", smi="Cc1ccccc1", cas="108-88-3",
         syn=["methylbenzene", "toluol"],
         ghs=["H225", "H304", "H315", "H336", "H361d", "H373"],
         qty=2500, unit="mL", min=250, bp=110.6, d=0.867,
         app="Colorless liquid / مایع بی‌رنگ",
         notes="Regulated solvent precursor in some jurisdictions."),
    dict(en="Chloroform", fa="کلروفرم", smi="ClC(Cl)Cl", cas="67-66-3",
         syn=["trichloromethane"],
         ghs=["H302", "H315", "H319", "H331", "H351", "H361", "H372", "H400", "H410"],
         qty=1000, unit="mL", min=100, bp=61.2, d=1.489,
         app="Colorless liquid / مایع بی‌رنگ",
         notes="Toxic; suspected carcinogen; strict fume-hood use."),
    dict(en="Isopropanol (IPA)", fa="ایزوپروپانول", smi="CC(C)O", cas="67-63-0",
         syn=["isopropyl alcohol", "2-propanol"],
         ghs=["H225", "H302", "H319", "H336"], qty=2500, unit="mL", min=250,
         bp=82.6, d=0.786, app="Colorless liquid / مایع بی‌رنگ"),

    # ========================== ACIDS & BASES ==============================
    dict(en="Hydrochloric acid (37%)", fa="هیدروکلریک اسید ۳۷٪", smi="Cl", cas="7647-01-0",
         syn=["HCl", "muriatic acid", "جوهر نمک"],
         ghs=["H290", "H314", "H335"], qty=2500, unit="mL", min=250,
         d=1.19, app="Colorless fuming liquid / مایع بی‌رنگ بخارکننده",
         notes="Corrosive; regulated precursor (drug-precursor lists); add acid to water."),
    dict(en="Sulfuric acid (98%)", fa="سولفوریک اسید ۹۸٪", smi="OS(=O)(=O)O", cas="7664-93-9",
         syn=["H2SO4", "جوهر گوگرد"],
         ghs=["H290", "H314"], qty=2500, unit="mL", min=250,
         d=1.84, app="Colorless oily liquid / مایع روغنی بی‌رنگ",
         notes="Strongly corrosive & dehydrating; violent exotherm with water; regulated precursor."),
    dict(en="Acetic acid (glacial)", fa="استیک اسید خالص", smi="CC(O)=O", cas="64-19-7",
         syn=["glacial acetic acid", "vinegar acid", "اسید استیک"],
         ghs=["H226", "H314"], qty=2500, unit="mL", min=250,
         mp=16.6, bp=118.0, d=1.049, app="Colorless liquid / مایع بی‌رنگ"),
    dict(en="Nitric acid (65%)", fa="نیتریک اسید ۶۵٪", smi="O[N+](=O)[O-]", cas="7697-37-2",
         syn=["HNO3", "جوهر شوره"],
         ghs=["H272", "H290", "H314", "H331"], qty=1000, unit="mL", min=100,
         d=1.39, app="Colorless to yellow liquid / مایع بی‌رنگ تا زرد",
         notes="Strong oxidiser — never mix with organics/solvents without a procedure."),
    dict(en="Formic acid", fa="فرمیک اسید", smi="OC=O", cas="64-18-6",
         syn=["methanoic acid"],
         ghs=["H290", "H302", "H314", "H331"], qty=500, unit="mL", min=50,
         bp=100.8, d=1.220, app="Colorless liquid / مایع بی‌رنگ"),
    dict(en="Trifluoroacetic acid (TFA)", fa="تری‌فلوئورواستیک اسید", smi="OC(=O)C(F)(F)F",
         cas="76-05-1", syn=["TFA"],
         ghs=["H290", "H302", "H314", "H330"], qty=500, unit="mL", min=50,
         bp=72.4, d=1.53, app="Colorless liquid / مایع بی‌رنگ"),
    dict(en="Sodium hydroxide", fa="سدیم هیدروکسید", smi="[Na+].[OH-]", cas="1310-73-2",
         syn=["NaOH", "caustic soda", "سود سوزآور"],
         ghs=["H290", "H314"], qty=1000, unit="g", min=100,
         mp=318.0, app="White pellets / گرانول سفید",
         notes="Exothermic dissolution in water; corrosive to metals."),
    dict(en="Potassium hydroxide", fa="پتاسیم هیدروکسید", smi="[K+].[OH-]", cas="1310-58-3",
         syn=["KOH", "caustic potash"],
         ghs=["H290", "H314"], qty=1000, unit="g", min=100,
         mp=360.0, app="White pellets / گرانول سفید"),
    dict(en="Sodium carbonate", fa="سدیم کربنات", smi="[Na+].[Na+].[O-]C([O-])=O",
         cas="497-19-8", syn=["Na2CO3", "soda ash"],
         ghs=["H315", "H319"], qty=1000, unit="g", min=100,
         mp=851.0, app="White powder / پودر سفید"),
    dict(en="Potassium carbonate", fa="پتاسیم کربنات", smi="[K+].[K+].[O-]C([O-])=O",
         cas="584-08-7", syn=["K2CO3", "potash"],
         ghs=["H315", "H319"], qty=1000, unit="g", min=100,
         mp=891.0, app="White powder / پودر سفید"),
    dict(en="Sodium bicarbonate", fa="سدیم بی‌کربنات", smi="[Na+].OC([O-])=O",
         cas="144-55-8", syn=["NaHCO3", "baking soda", "جوش شیرین"],
         ghs=[], qty=1000, unit="g", min=100, app="White powder / پودر سفید"),
    dict(en="Cesium carbonate", fa="سزیم کربنات", smi="[Cs+].[Cs+].[O-]C([O-])=O",
         cas="534-17-8", syn=["Cs2CO3"],
         ghs=[], qty=250, unit="g", min=50, mp=610.0, app="White powder / پودر سفید",
         notes="Verify hazards against supplier SDS."),
    dict(en="Triethylamine", fa="تری‌اتیل‌آمین", smi="CCN(CC)CC", cas="121-44-8",
         syn=["TEA", "Et3N"],
         ghs=["H225", "H302", "H311", "H314", "H331"], qty=1000, unit="mL", min=100,
         bp=89.0, d=0.726, app="Colorless liquid / مایع بی‌رنگ",
         notes="Flammable, corrosive, toxic; strong odour — fume hood."),
    dict(en="N,N-Diisopropylethylamine (DIPEA)", fa="دی‌ایزوپروپیل‌اتیل‌آمین",
         smi="CCN(C(C)C)C(C)C", cas="7087-68-5", syn=["Hünig's base", "DIPEA", "DIEA"],
         ghs=["H226", "H302", "H314"], qty=500, unit="mL", min=50,
         bp=127.0, d=0.742, app="Colorless liquid / مایع بی‌رنگ"),
    dict(en="Pyridine", fa="پیریدین", smi="c1ccncc1", cas="110-86-1",
         syn=[], ghs=["H225", "H302", "H312", "H332"], qty=500, unit="mL", min=50,
         bp=115.2, d=0.982, app="Colorless liquid / مایع بی‌رنگ",
         notes="Noxious odour; flammable; fume hood."),
    dict(en="4-Dimethylaminopyridine (DMAP)", fa="دی‌متیل‌آمینوپیریدین",
         smi="CN(C)c1ccncc1", cas="1122-58-3", syn=["DMAP"],
         ghs=["H301", "H311", "H314", "H331"], qty=100, unit="g", min=25,
         mp=113.0, app="White solid / جامد سفید",
         notes="HIGHLY TOXIC — weigh with care, gloves, fume hood."),
    dict(en="p-Toluenesulfonic acid", fa="پارا-تولوئن‌سولفونیک اسید",
         smi="Cc1ccc(S(O)(=O)=O)cc1", cas="104-15-4", syn=["pTsOH", "tosylic acid"],
         ghs=["H290", "H302", "H314"], qty=250, unit="g", min=50,
         mp=104.0, app="White solid / جامد سفید"),
    dict(en="Citric acid", fa="سیتریک اسید", smi="OC(=O)CC(O)(CC(=O)O)C(=O)O",
         cas="77-92-9", syn=["اسید سیتریک"],
         ghs=["H318"], qty=250, unit="g", min=50, mp=153.0, app="White crystals / بلور سفید"),

    # ========================= COMMON REAGENTS =============================
    dict(en="Thionyl chloride", fa="تیونیل کلرید", smi="ClS(Cl)=O", cas="7719-09-7",
         syn=["SOCl2"],
         ghs=["H290", "H302", "H314", "H330", "H335"], qty=500, unit="mL", min=50,
         bp=74.6, d=1.638, app="Colorless liquid / مایع بی‌رنگ",
         notes="Reacts violently with water releasing SO2/HCl; regulated precursor; fume hood."),
    dict(en="Oxalyl chloride", fa="اگزالیل کلرید", smi="ClC(=O)C(Cl)=O", cas="79-37-8",
         syn=["(COCl)2"],
         ghs=["H290", "H302", "H314", "H330"], qty=100, unit="mL", min=25,
         bp=63.0, d=1.488, app="Colorless liquid / مایع بی‌رنگ",
         notes="Water-reactive, releases CO/CO2/HCl; strict fume hood."),
    dict(en="Methanesulfonyl chloride", fa="متان‌سولفونیل کلرید", smi="CS(=O)(=O)Cl",
         cas="124-63-0", syn=["MsCl", "mesyl chloride"],
         ghs=["H290", "H302", "H314", "H330"], qty=100, unit="mL", min=25,
         d=1.48, app="Colorless liquid / مایع بی‌رنگ"),
    dict(en="Acetic anhydride", fa="استیک انیدرید", smi="CC(=O)OC(C)=O", cas="108-24-7",
         syn=["Ac2O"],
         ghs=["H226", "H302", "H314", "H330", "H335"], qty=500, unit="mL", min=50,
         bp=140.0, d=1.082, app="Colorless liquid / مایع بی‌رنگ",
         notes="REGULATED drug precursor (List II) — store securely, log usage."),
    dict(en="Di-tert-butyl dicarbonate (Boc2O)", fa="دی‌ترت‌بوتیل دی‌کربنات",
         smi="CC(C)(C)OC(=O)OC(=O)OC(C)(C)C", cas="24424-99-5",
         syn=["Boc anhydride", "Boc2O"],
         ghs=["H315", "H319", "H335"], qty=250, unit="g", min=50,
         mp=22.0, app="White solid / جامد سفید"),
    dict(en="Sodium borohydride", fa="سدیم بوروهیدرید", smi="[Na+].[BH4-]", cas="16940-66-2",
         syn=["NaBH4"],
         ghs=["H260", "H301", "H311", "H314", "H331"], qty=250, unit="g", min=50,
         app="White powder / پودر سفید",
         notes="Water-reactive — releases flammable hydrogen gas; keep dry."),
    dict(en="Lithium aluminium hydride", fa="لیتیم آلومینیوم هیدرید", smi="[Li+].[AlH4-]",
         cas="16853-85-3", syn=["LAH", "LiAlH4"],
         ghs=["H260", "H301", "H311", "H314", "H331"], qty=100, unit="g", min=25,
         app="White-grey powder / پودر سفید-خاکستری",
         notes="VIOLENTLY water-reactive; Class D fire risk; never use water on fires."),
    dict(en="Sodium hydride (60% in oil)", fa="سدیم هیدرید ۶۰٪ در روغن", smi="[NaH]",
         cas="7646-69-7", syn=["NaH"],
         ghs=["H260", "H301", "H311", "H314", "H331"], qty=100, unit="g", min=25,
         app="Grey dispersion / دیسپرسیون خاکستری",
         notes="Pyrophoric when washed dry; releases H2 with moisture/water."),
    dict(en="Sodium metal", fa="سدیم فلزی", smi="[Na]", cas="7440-23-5",
         syn=["sodium"], ghs=["H260", "H314"], qty=100, unit="g", min=25,
         app="Silvery metal / فلز نقره‌ای",
         notes="Store under mineral oil; reacts violently with water."),
    dict(en="Magnesium turnings", fa="منیزیم", smi="[Mg]", cas="7439-95-4",
         syn=["Mg", "magnesium"], ghs=["H228"], qty=250, unit="g", min=50,
         app="Silvery turnings / تراشه نقره‌ای",
         notes="Flammable solid; intense white flame; Class D fire risk."),
    dict(en="Zinc dust", fa="گرد روی", smi="[Zn]", cas="7440-66-6",
         syn=["zinc powder", "روی"],
         ghs=["H260", "H301", "H315", "H319", "H330", "H400", "H410"],
         qty=250, unit="g", min=50, app="Grey powder / پودر خاکستری",
         notes="Water-reactive; very toxic to aquatic life."),
    dict(en="Iron powder", fa="گرد آهن", smi="[Fe]", cas="7439-89-6",
         syn=["iron"], ghs=["H228"], qty=250, unit="g", min=50,
         app="Grey powder / پودر خاکستری"),
    dict(en="Palladium on carbon (10%)", fa="پالادیوم روی کربن ۱۰٪", smi="[Pd]",
         cas="7440-05-3", syn=["Pd/C", "palladium charcoal"],
         ghs=["H228", "H261"], qty=25, unit="g", min=5,
         app="Black powder / پودر سیاه",
         notes="Pyrophoric when dry — keep moist, handle under inert gas; precious metal."),
    dict(en="Potassium permanganate", fa="پتاسیم پرمنگنات",
         smi="[K+].[O-][Mn](=O)(=O)=O", cas="7722-64-7", syn=["KMnO4"],
         ghs=["H272", "H302", "H314", "H410"], qty=250, unit="g", min=50,
         app="Purple crystals / بلورهای بنفش",
         notes="Strong oxidiser; regulated precursor (List III); stains skin."),
    dict(en="Hydrogen peroxide (30%)", fa="هیدروژن پروکسید ۳۰٪", smi="OO",
         cas="7722-84-1", syn=["H2O2"],
         ghs=["H271", "H302", "H314", "H335"], qty=1000, unit="mL", min=100,
         d=1.11, app="Colorless liquid / مایع بی‌رنگ",
         notes="Strong oxidiser at 30%; causes severe burns."),
    dict(en="m-Chloroperoxybenzoic acid (mCPBA)", fa="متاکلروپری‌بنزوئیک اسید",
         smi="O=C(OO)c1cccc(Cl)c1", cas="937-14-4", syn=["mCPBA"],
         ghs=["H271", "H302", "H315", "H319", "H335"], qty=100, unit="g", min=25,
         app="White solid / جامد سفید",
         notes="Oxidiser; shock-sensitive when dry — store cold, keep moist (~77% max)."),
    dict(en="N-Bromosuccinimide (NBS)", fa="ان-برموسوکسین‌امید", smi="O=C1CCC(=O)N1Br",
         cas="128-08-5", syn=["NBS"],
         ghs=["H272", "H302", "H314", "H330", "H400", "H410"], qty=100, unit="g", min=25,
         mp=173.0, app="White solid / جامد سفید", notes="Oxidiser; corrosive; toxic."),
    dict(en="Iodine", fa="ید", smi="II", cas="7553-56-1",
         syn=["I2"],
         ghs=["H302", "H312", "H315", "H319", "H332", "H334", "H372", "H400", "H410"],
         qty=100, unit="g", min=25, mp=113.7, app="Dark violet crystals / بلور بنفش تیره",
         notes="Vapour irritates; stains; corrosive to metals."),
    dict(en="N,N'-Dicyclohexylcarbodiimide (DCC)", fa="دی‌سیکلوهگزیل‌کربودی‌ایمید",
         smi="C1CCC(N=C=NC2CCCCC2)CC1", cas="538-75-0", syn=["DCC"],
         ghs=["H302", "H315", "H319", "H334", "H410"], qty=100, unit="g", min=25,
         mp=103.0, app="White solid / جامد سفید",
         notes="Sensitiser — avoid inhalation of dust; DCU by-product filtration."),
    dict(en="EDC hydrochloride", fa="ای‌دی‌سی هیدروکلراید", smi="CCN=C=NCCCN(C)C.Cl",
         cas="25952-53-8", syn=["EDC·HCl", "EDAC"],
         ghs=["H302", "H315", "H319", "H334"], qty=100, unit="g", min=25,
         app="White solid / جامد سفید", notes="Sensitiser; hygroscopic — store cold & dry."),
    dict(en="Triphenylphosphine", fa="تری‌فنیل‌فسفین",
         smi="P(c1ccccc1)(c1ccccc1)c1ccccc1", cas="603-35-0", syn=["PPh3"],
         ghs=["H302", "H315", "H319", "H335", "H400", "H410"], qty=250, unit="g", min=50,
         mp=80.0, app="White solid / جامد سفید"),

    # ==================== SIMPLE BUILDING BLOCKS ===========================
    dict(en="Phenol", fa="فنل", smi="Oc1ccccc1", cas="108-95-2",
         syn=["carbolic acid", "hydroxybenzene"],
         ghs=["H226", "H301", "H311", "H314", "H331", "H341", "H373"],
         qty=250, unit="g", min=50, mp=40.5, bp=181.7,
         app="White-pink crystals / بلور سفید-صورتی",
         notes="Toxic & corrosive; melts near room temperature."),
    dict(en="Aniline", fa="آنیلین", smi="Nc1ccccc1", cas="62-53-3",
         syn=["aminobenzene", "phenylamine"],
         ghs=["H227", "H301", "H311", "H331", "H351", "H372", "H400", "H410"],
         qty=250, unit="mL", min=50, bp=184.0, d=1.022,
         app="Colorless to brown liquid / مایع بی‌رنگ تا قهوه‌ای",
         notes="Toxic by all routes; suspected carcinogen; fume hood."),
    dict(en="Benzaldehyde", fa="بنزآلدهید", smi="O=Cc1ccccc1", cas="100-52-7",
         syn=[], ghs=["H227", "H302", "H315", "H319", "H335"], qty=250, unit="mL", min=50,
         bp=178.0, d=1.044, app="Colorless liquid / مایع بی‌رنگ",
         notes="Regulated precursor in some jurisdictions."),
    dict(en="Benzyl alcohol", fa="بنزیل الکل", smi="OCc1ccccc1", cas="100-51-6",
         syn=["BnOH", "phenylmethanol"],
         ghs=["H302", "H315", "H319", "H335"], qty=250, unit="mL", min=50,
         bp=205.0, d=1.045, app="Colorless liquid / مایع بی‌رنگ"),
    dict(en="Benzoic acid", fa="بنزوئیک اسید", smi="OC(=O)c1ccccc1", cas="65-85-0",
         syn=[], ghs=["H315", "H319", "H335"], qty=250, unit="g", min=50,
         mp=122.0, app="White solid / جامد سفید"),
    dict(en="Acetophenone", fa="استوفنون", smi="CC(=O)c1ccccc1", cas="98-86-2",
         syn=["methyl phenyl ketone"],
         ghs=["H302", "H315", "H319"], qty=100, unit="mL", min=25,
         mp=20.0, bp=202.0, app="Colorless liquid or solid / مایع یا جامد بی‌رنگ"),
    dict(en="Benzene", fa="بنزن", smi="c1ccccc1", cas="71-43-2",
         syn=[], ghs=["H225", "H304", "H315", "H319", "H340", "H350", "H372"],
         qty=500, unit="mL", min=50, bp=80.1, d=0.876,
         app="Colorless liquid / مایع بی‌رنگ",
         notes="KNOWN human carcinogen (leukemia) — avoid; prefer toluene as solvent."),
    dict(en="Urea", fa="اوره", smi="NC(N)=O", cas="57-13-6",
         syn=["carbamide"], ghs=[], qty=250, unit="g", min=50, mp=133.0,
         app="White crystals / بلور سفید"),
    dict(en="Ammonium chloride", fa="آمونیوم کلرید", smi="[NH4+].[Cl-]", cas="12125-02-9",
         syn=["NH4Cl", "sal ammoniac", "نشادر"],
         ghs=["H302", "H319"], qty=500, unit="g", min=100, app="White powder / پودر سفید"),
    dict(en="Sodium chloride", fa="سدیم کلرید", smi="[Na+].[Cl-]", cas="7647-14-5",
         syn=["NaCl", "table salt", "نمک طعام"],
         ghs=[], qty=1000, unit="g", min=200, app="White crystals / بلور سفید"),
    dict(en="Magnesium sulfate (anhydrous)", fa="منیزیم سولفات بدون آب",
         smi="[Mg+2].[O-]S([O-])(=O)=O", cas="7487-88-9", syn=["MgSO4", "drying agent"],
         ghs=[], qty=1000, unit="g", min=200, app="White powder / پودر سفید",
         notes="Common drying agent for organic extracts."),
    dict(en="Sodium sulfate (anhydrous)", fa="سدیم سولفات بدون آب",
         smi="[Na+].[Na+].[O-]S([O-])(=O)=O", cas="7757-82-6", syn=["Na2SO4", "drying agent"],
         ghs=[], qty=1000, unit="g", min=200, app="White powder / پودر سفید",
         notes="Common drying agent for organic extracts."),
    dict(en="Calcium chloride (anhydrous)", fa="کلسیم کلرید بدون آب",
         smi="[Ca+2].[Cl-].[Cl-]", cas="10043-52-4", syn=["CaCl2"],
         ghs=["H319"], qty=500, unit="g", min=100, app="White granules / گرانول سفید",
         notes="Drying agent; exothermic with water; not for acidic extracts."),
    dict(en="Potassium iodide", fa="پتاسیم یدید", smi="[K+].[I-]", cas="7681-11-0",
         syn=["KI"], ghs=[], qty=250, unit="g", min=50, app="White crystals / بلور سفید"),
    dict(en="Copper(II) sulfate", fa="مس(II) سولفات", smi="[Cu+2].[O-]S([O-])(=O)=O",
         cas="7758-98-7", syn=["CuSO4", "بلور مس"],
         ghs=["H302", "H315", "H319", "H410"], qty=250, unit="g", min=50,
         app="Blue-white powder / پودر آبی-سفید"),
    dict(en="Silica gel 60 (for chromatography)", fa="سیلیکاژل ۶۰ (کروماتوگرافی)",
         smi="", cas="112926-00-8", syn=["SiO2", "silica"],
         ghs=[], qty=2000, unit="g", min=500, app="White beads / دانه سفید",
         notes="No SMILES — bulk stationary phase, not a molecular compound."),
]
